### ISSUE TITLE
[bug] PHP Fatal error:  Cannot redeclare EPFL\\Plugins\\Gutenberg\\StudentProjects\\sortByProjectName()

### ISSUE THREAD

**Issue by obieler** [epfl-si/wp-gutenberg-epfl#347]
**Description**

I had an error (500) when I call: https://inside.epfl.ch/projets-etudiants-sti/wp-json/wp/v2/pages
(or from a pod: `curl -k -H "Host: inside.epfl.ch" https://httpd-inside:8443/projets-etudiants-sti/wp-json/wp/v2/pages`

Crash here (function already declared):
https://github.com/epfl-si/wp-gutenberg-epfl/blob/ddf762842e99dac4d9f30708eb0ec4edf94e4ab1/frontend/epfl-student-projects/controller.php#L61

**Error log**

`error_log.httpd-inside-166-zxhxk.20220711:[Mon Jul 11 14:59:11.871241 2022] [php7:error] [pid 94681] [client 172.31.46.182:46038] PHP Fatal error:  Cannot redeclare EPFL\\Plugins\\Gutenberg\\StudentProjects\\sortByProjectName() (previously declared in /wp/5.5.9/wp-content/plugins/wp-gutenberg-epfl/frontend/epfl-student-projects/controller.php:61) in /wp/5.5.9/wp-content/plugins/wp-gutenberg-epfl/frontend/epfl-student-projects/controller.php on line 61`

**Comment by jdelasoie** [comment]
Should be good

**Comment by obieler** [comment]
> Should be good

Thanks JD :+1:
